### ISSUE TITLE
Directory support???

### ISSUE THREAD

**Issue by gautamajay52** [AndriiVal/images-to-pdf#1]
Instead of taking image list as input...
why can't it take all image froma specific directory???
That will be easy.

**Comment by AndriiVal** [comment]
Thanks for the comment. I wrote this script quickly for my needs. In the future, if there is time, I will improve the code.

**Comment by AndriiVal** [comment]
Now support directory of images

**Comment by gautamajay52** [comment]
Not working!!

should i show error or u can try.🤗

**Comment by gautamajay52** [comment]
I have got this code on Google...its everything is fine..its resolution and all....
But only problem is that it is saving a separate pdf for all the images...

I want a pdf of all the image in a directory.

`from PIL import Image
import os

os.listdir()
def makePdf(imageDir, SaveToDir):
  os.chdir(imageDir)
  try:
    for j in os.listdir(os.getcwd()):
      os.chdir(imageDir)
      fname, fext = os.path.splitext(j)
      newfilename= fname + ".pdf"
      im = Image.open(fname + fext)
      if im.mode == "RGBA":
        im = im.convert("RGB")
      os.chdir(SaveToDir)
      if not os.path.exists(newfilename):
      	im.save(newfilename, "PDF", resolution=100.0)
  except Exception as e:
    print(e)
        
imageDir = r'/data/data/com.termux/files/home/ts/emage' # your imagedirectory path
SaveToDir = r'/data/data/com.termux/files/home' # diretory in which you want to save the pdfs
makePdf(imageDir, SaveToDir)`

if u can fix😔😔

**Comment by AndriiVal** [comment]
you forked old version, i update the script, now it must work

**Comment by gautamajay52** [comment]
> you forked old version, i update the script, now it must work

getting this error---
Traceback (most recent call last):
  File "p6f.py", line 21, in <module>
    if os.path.isfile(fullname) and not has_hidden_attribute(fullname):
  File "p6f.py", line 13, in has_hidden_attribute
    return bool(os.stat(filepath).st_file_attributes & stat.FILE_ATTRIBUTE_HIDDEN)
AttributeError: 'os.stat_result' object has no attribute 'st_file_attributes'

**Comment by AndriiVal** [comment]
just checked on Python 3.7.3 - work good

**Comment by gautamajay52** [comment]
i am using python 3.8.3.

And still getting that above error.
Using in termux

![Screenshot_20200613-102426__01__01__01](https://user-images.githubusercontent.com/25435568/84560305-47208280-ad60-11ea-9ccd-5d9d606dc0b0.jpg)

p6f.py is that file edited due to long name.

**Comment by AndriiVal** [comment]
termux, use Android? Try this:

#! /usr/bin/python3.7
# -*- coding: utf-8 -*-

# Author: Andrii Valchuk

import os
import time

from wand.image import Image as wimg
from progress.bar import IncrementalBar

imgDir = input('Enter a directory of images: ')
fileName = input('Enter pdf file name: ')

filesList = os.listdir(imgDir)
fileList = []
for name in filesList:
    fullname = os.path.join(imgDir, name)
    if os.path.isfile(fullname) and (fullname.endswith('.png') or fullname.endswith('.jpg')):
        fileList.append(fullname)

print('Start conversion, pleas wait...')

bar = IncrementalBar('Convert', max = len(fileList))
img = wimg()

try:
    for file in fileList:
        img.read(filename=file)
        converted = img.convert('pdf')
        converted.save(filename=fileName)
        bar.next()
        time.sleep(.1)
except Exception as ex:
    print('\nCannot convert image to pdf: %s', ex)

bar.finish()

print("Finish\n")

**Comment by gautamajay52** [comment]
> termux, use Android? Try this:
> 
> #! /usr/bin/python3.7
> 
> # -_- coding: utf-8 -_-
> # Author: Andrii Valchuk
> import os
> import time
> 
> from wand.image import Image as wimg
> from progress.bar import IncrementalBar
> 
> imgDir = input('Enter a directory of images: ')
> fileName = input('Enter pdf file name: ')
> 
> filesList = os.listdir(imgDir)
> fileList = []
> for name in filesList:
> fullname = os.path.join(imgDir, name)
> if os.path.isfile(fullname) and (fullname.endswith('.png') or fullname.endswith('.jpg')):
> fileList.append(fullname)
> 
> print('Start conversion, pleas wait...')
> 
> bar = IncrementalBar('Convert', max = len(fileList))
> img = wimg()
> 
> try:
> for file in fileList:
> img.read(filename=file)
> converted = img.convert('pdf')
> converted.save(filename=fileName)
> bar.next()
> time.sleep(.1)
> except Exception as ex:
> print('\nCannot convert image to pdf: %s', ex)
> 
> bar.finish()
> 
> print("Finish\n")

Thanks...
This worked!!

Have u seen the above code???
Why is it making a pdf file all images separately instead of make a pdf file containing all images like ur code?????

**Comment by AndriiVal** [comment]
becose it create every time new pdf in cicle

**Comment by gautamajay52** [comment]
> becose it create every time new pdf in cicle

okay thanks.
